### ISSUE TITLE
Todo: Update website info

### ISSUE THREAD

**Issue by StephenXie** [frc-7419/frc-7419.github.io#3]
- [x] 1. Get Ms. Lina picture.
- [x] 2. Break our story into paragraphs, general- grew out of FTC,  then 7419 FRC.  
- [x] 3. Outreach, talk up how every student participates in outreach as a school commitment and highlight a few, then the team outreach as STEM.  
- [x] 4. Student leadership, preliminary blurb (leadership spans all grade levels, establishes information and training profile, etc); 
- [x] 5. add graduating year after the name. 
- [ ] 5. Sponsors. Dr. Arac QLS, his commitment to the team, take out monies donated, 
- [x] 6. In the Sponsors page, list who has helped the program, no need to explain who they are (none of them are sponsoring this season).

**Comment by pryme-svg** [comment]
1 is done I just need a pic
